#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt skwp

set -o vi

# Aliases
alias cfg="$(which git) --git-dir=$HOME/.cfg/ --work-tree=$HOME"
alias psgrep='ps aux | grep'

# Source zplug
export ZPLUG_HOME=$HOME/.cfg/zplug
source $ZPLUG_HOME/init.zsh

zplug "supercrabtree/k"

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  else
    echo
  fi
fi

zplug load

eval "$(tmuxifier init -)"
