#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt paradox2

set -o vi

# Aliases
alias cfg="$(which git) --git-dir=$HOME/.cfg/ --work-tree=$HOME"
alias dockerc='docker-compose'
alias tmux-t='tmux attach -t'
alias tmuxk='tmux kill-session -t'
alias ber='bundle exec rspec'

export GOPATH="$HOME/go"
source "$HOME/dotfiles/secret_keys.sh"

psgrep() {
  ps aux | grep --color=always $1 | grep -v grep | less -RFX
}

goel() {
  cd $GOPATH/src/github.com/EmpregoLigado
}

devel() {
  cd $HOME/Dev/el
}

export PATH=$PATH:$GOPATH/bin:$HOME/bin
fpath=(/usr/local/share/zsh-completions $fpath)

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
